---
apiVersion: tarantool.io/v1alpha1
kind: Cluster
metadata:
  name: {{ .Values.ClusterName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      tarantool.io/cluster-id: {{ .Values.ClusterName }}
---
{{- range .Values.RoleConfig }}
{{- $r := .RolesToAssign | toJson | quote }}
apiVersion: tarantool.io/v1alpha1
kind: Role
metadata:
  name: {{ .RoleName | replace "_" "" }}
  namespace: {{ $.Values.namespace }}
  labels:
    tarantool.io/cluster-id: {{ $.Values.ClusterName }}
    tarantool.io/role: {{ .RoleName }}
  annotations:
    tarantool.io/rolesToAssign: {{ $r }}
    # Configure failover method
    {{ if $.Values.TarantoolConfig.UseStateboardFailover }}
    tarantool.io/failoverMode: "stateful-tarantool"
    {{ else if $.Values.TarantoolConfig.UseConsulFailover }}
    tarantool.io/failoverMode: "stateful-consul"
    {{ else }}
    tarantool.io/failoverMode: "eventual"
    {{ end }}
spec:
  selector:
    matchLabels:
      tarantool.io/replicaset-template: "{{ .RoleName }}-template"
  numReplicasets: {{ .ReplicaSetCount }}
---
apiVersion: tarantool.io/v1alpha1
kind: ReplicasetTemplate
metadata:
  name: "{{ .RoleName | replace "_" "" }}-template"
  namespace: {{ $.Values.namespace }}
  labels:
    tarantool.io/cluster-id: {{ $.Values.ClusterName }}
    tarantool.io/replicaset-template: "{{ .RoleName }}-template"
    tarantool.io/role: {{ .RoleName }}
    {{ if .VshardGroupName }}
    tarantool.io/vshardGroupName: "{{ .VshardGroupName }}"
    {{ end}}
    {{ if .UseVshardGroups }}
    tarantool.io/useVshardGroups: "{{ .UseVshardGroups }}"
    {{ else }}
    tarantool.io/useVshardGroups: "0"
    {{ end }}
  annotations:
    tarantool.io/rolesToAssign: {{ $r }}
spec:
  replicas: {{ .ReplicaCount }}
  serviceName: {{ .RoleName }}
  selector:
    matchLabels:
      tarantool.io/pod-template: "{{ .RoleName }}-pod-template"
  volumeClaimTemplates:
    - metadata:
        name: www
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .DiskSize }}
  template:
    metadata:
      labels:
        tarantool.io/cluster-id: {{ $.Values.ClusterName }}
        tarantool.io/pod-template: "{{ .RoleName }}-pod-template"
        # Configure use of vshard groups
        {{ if .UseVshardGroups }}
        tarantool.io/useVshardGroups: "{{ .UseVshardGroups }}"
        {{ else }}
        tarantool.io/useVshardGroups: "0"
        {{ end }}
        environment: "{{ $.Values.ClusterEnv }}"
      annotations:
        prometheus.io/path: "{{ $.Values.Prometheus.path }}"
        prometheus.io/port: "{{ $.Values.Prometheus.port}}"
        prometheus.io/scrape: "true"
        tarantool.io/rolesToAssign: {{ $r }}
    spec:
      terminationGracePeriodSeconds: 10
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      updateStrategy:
        type: OnDelete
      securityContext:
        fsGroup: 1000
        capabilities:
          add: ["SYS_ADMIN"]
      containers:
        - name: pim-storage
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
          volumeMounts:
            - name: www
              mountPath: "/data"
          resources:
            requests:
              cpu: "{{ .CPUallocation }}"
              memory: "{{ .MemtxMemoryMB }}M"
            limits:
              cpu: "{{ .CPUallocation }}"
              memory: "{{ .MemtxMemoryMB }}M"
          ports:
            - containerPort: 3301
              protocol: TCP
              name: app
            - containerPort: 3301
              protocol: UDP
              name: app-udp
            - containerPort: 8081
              protocol: TCP
              name: http
          env:
            - name: ENVIRONMENT
              value: "{{ $.Values.ClusterEnv }}"
            - name: TARANTOOL_CLUSTER_COOKIE
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: cluster.cookie
            - name: TARANTOOL_INSTANCE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TARANTOOL_WORK_DIR
              value: "{{ $.Values.TarantoolConfig.WorkingDir }}"
            - name: TARANTOOL_STORAGE_DIR
              value: "{{ $.Values.TarantoolConfig.StorageDir }}"
            - name: TARANTOOL_MEMTX_MEMORY
              value: "{{ mul .MemtxMemoryMB 1048576 }}"
            - name: TARANTOOL_BUCKET_COUNT
              value: "30000"
            {{  if $.Values.TarantoolConfig.UseJSONlogging }}
            - name: TARANTOOL_LOG_FORMAT
              value: json
            {{ end }}
            - name: TARANTOOL_ADVERTISE_TMP
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: TARANTOOL_ADVERTISE_HOST
              value: "$(TARANTOOL_ADVERTISE_TMP).{{ $.Values.ClusterName }}.{{ $.Values.namespace }}.svc.cluster.local"
            - name: TARANTOOL_ADVERTISE_URI
              value: "$(TARANTOOL_ADVERTISE_HOST):3301"
            - name: TARANTOOL_ALL_SHARD_GROUPS_LIST
              value: "{{- join "," $.Values.AllShardGroups }}"
            - name: VPC_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{ if (.ConsulRoleTag) }}
            - name: CONSUL_ROLE_TAG
              value: {{ .ConsulRoleTag }}
            {{ end }}
            - name: CONSUL_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: cluster-config
                  key: consul.token
            - name: CONSUL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{ if ($.Values.efsVolumeId) }}
            - name: EFS_ID
              value: {{ $.Values.efsVolumeId }}
            {{ end }}
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .RoleName | replace "_" "-" }}
  namespace: {{ $.Values.namespace }}
  labels:
    tarantool.io/role: {{ .RoleName }}
spec:
  ports:
    - port: 8081
      name: web
      protocol: TCP
    - port: 3301
      name: app
      protocol: TCP
  selector:
    tarantool.io/role: {{ .RoleName }}
---
{{- end }}
---
