[service]
dockerfile = 'build/Dockerfile'
docker_build_dir = '.'
eks_cluster = 'eks-dev'
app_name = 'tarantool-operator'

namespaces = [
    'chat',
    'databucketer',
    'notifylocal',
    'presence',
    'reporting',
    'userscripting',
    'userlog',
]

regions = [
    'eu-west-1',
]

deployment.type = 'helm'
deployment.helm_chart = './ci/helm-chart'

deployment.extra_helm_opts = [
    # namespaces are created implicitly, pass this arg to ensure they are
    #  created on new deployments
    '--create-namespace',
]
