# Default values for tarantool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

ClusterEnv: dev
ClusterName: example

namespace: example

image:
  repository: 150395319802.dkr.ecr.eu-west-1.amazonaws.com/tt-kubernetes
  tag: examples-kv-1
  pullPolicy: IfNotPresent

BackupImage:
  repository: 150395319802.dkr.ecr.eu-west-1.amazonaws.com/tarantool-backups
  tag: dev-latest

TarantoolConfig:
  WorkingDir: /opt/tarantool
  StorageDir: /data
  EnableBackups: false
  UseStateboardFailover: true
  UseConsulFailover: false
  UseJSONlogging: true

service:
  type: ClusterIP
  port: 8081

Prometheus:
  port: 8081
  path: /metrics

AllShardGroups: []

RoleConfig:
  - RoleName: api
    ReplicaCount: 3
    ReplicaSetCount: 1
    DiskSize: 1Gi
    CPUallocation: 0.25
    MemtxMemoryMB: 256
    RolesToAssign:
      - router

  - RoleName: storage
    ReplicaCount: 3
    ReplicaSetCount: 1
    DiskSize: 1Gi
    CPUallocation: 0.25
    MemtxMemoryMB: 256
    RolesToAssign:
      - storage
