[service]
dockerfile = 'build/Dockerfile'
docker_build_dir = '.'
eks_cluster = 'eks-dev'
namespace = 'notifylocal'
app_name = 'tarantool-operator'

regions = [
    'eu-west-1',
]

deployment.type = 'helm'
deployment.helm_chart = './ci/helm-chart'
